### Variáveis globais
#@baseUrl = http://localhost:8080
@baseUrl = https://steadfast-connection-dev.up.railway.app
@contentType = application/json

### ============================================================================
### Listar todas as feature flags
# @name listFeatures
GET {{baseUrl}}/features 
### ============================================================================
### Obter status de uma feature flag específica
# @name getFeature
GET  {{baseUrl}}/features/feature:admin:frontend
### ============================================================================
### criar ou editar uma features flag
# @name createOrUpdateFeature
POST  {{baseUrl}}/features/admin:frontend:menu:keys
Content-Type: {{contentType}}

{
    "enabled": true,
    "description": "Habilita o menu de scan no frontend"
}
### ============================================================================
### Buscar chave específica
# @name getKey
GET {{baseUrl}}/keys/user:alice